fixes #96
Entropy-Foundation/aptos-core pull request #98
Opened 2024-10-04 08:52 UTC by sjoshisupra

fixes #96

2024-10-04 12:38 UTC, isaacdoidge requested changes
Looks good, just formatting issues to address.

2024-10-04 12:38 UTC, isaacdoidge commented on aptos-move/framework/supra-framework/sources/vesting_without_staking.move
> +            vesting_record.last_vested_period = next_period_to_vest-1;
Please fix the formatting of these two lines.

2024-10-05 11:27 UTC, isaacdoidge approved these changes

2024-10-05 12:04 UTC, merged

2024-10-07 02:02 UTC, axiongsupra commented
LGTM!